import {test} from "@playwright/test";

test("demonstrating automating nested frames",async ({page})=>{
    await page.goto("https://letcode.in/frame");
    const parentFrame = await page.frameLocator("#firstFr");
    await parentFrame.locator("//input[@name='fname']").fill("Arun");
    await parentFrame.locator("//input[@name='lname']").fill("Motoori");
    const childFrame = await parentFrame.frameLocator("//iframe[@title='Inner Frame']");
    await childFrame.locator("//input[@name='email']").fill("a@b.com");
});

test("demonstrating automating nested frames - complex example",async ({page})=>{
    await page.goto("https://the-internet.herokuapp.com/nested_frames");
    const parentFrame = await page.frameLocator("[name='frame-top']");
    const childLeftFrame = await parentFrame.frameLocator("[name='frame-left']");
    const leftText = await childLeftFrame.locator("body").innerText();
    console.log(leftText);
    const childMiddleFrame = await parentFrame.frameLocator("[name='frame-middle']");
    const middleText = await childMiddleFrame.locator("#content").innerText();
    console.log(middleText);
    const childRightFrame = await parentFrame.frameLocator("[name='frame-right']");
    const rightText = await childRightFrame.locator("body").innerText();
    console.log(rightText);
    const frameTwo = await page.frameLocator("[name='frame-bottom']");
    const bottomText = await frameTwo.locator("body").innerText();
    console.log(bottomText);
});

test("demonstrating - by handling frames using frame command",async ({page})=>{
    await page.goto("https://docs.oracle.com/javase/8/docs/api/");
    const frameOne = await page.frameLocator("[name='classFrame']");
    await frameOne.locator("//a[text()='Description']").click();
});

test("demonstrating - by handling frames using contentFrame",async ({page})=>{
    await page.goto("https://docs.oracle.com/javase/8/docs/api/");
    const frameElement = await page.locator("[name='classFrame']");
    const frameOne = await frameElement.contentFrame();
    await frameOne.locator("//a[text()='Description']").click();
});

test("demonstrating - by handing frames autogenerated using picklocator",async ({page})=>{
    await page.goto("https://letcode.in/frame");
    await page.locator('iframe[name="firstFr"]').contentFrame().getByRole('textbox', { name: 'Enter name' }).fill("Arun");
    await page.locator('iframe[name="firstFr"]').contentFrame().getByRole('textbox', { name: 'Enter email' }).fill("Motoori");
    await page.locator('iframe[name="firstFr"]').contentFrame().locator('iframe[title="Inner Frame"]').contentFrame().getByRole('textbox', { name: 'Enter email' }).fill("a@b.com");
});